version: '3.8'
services:
  aapanel:
    image: aapanel/aapanel:lib
    container_name: aapanel
    ports:
      - "8886:7800"
      - "22:21"
      - "443:443"
      - "80:80"
      - "889:888"
    volumes:
      - ./website_data:/www/wwwroot
      - ./mysql_data:/www/server/data
      - ./vhost:/www/server/panel/vhost
    restart: always
    environment:
      TZ: Asia/Jakarta

networks:
  default:
    driver: bridge
